Update build.gradle
The Issue no 11 is resolved by changing -
runProguard false to minifyEnabled false
Note - Gradle must be 2.2 or above to use minifyEnabled

Also build tools changed to 21.0.0 to resolve following error - 

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Multi dex requires Build Tools 21.0.0 / Current: 20